#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
repos:
- repo: local
  hooks:
    - id: sbt-compile-package
      name: sbt-compile-package
      entry: bash -c 'sbt compile package'
      language: system
      types: [file]
      pass_filenames: false
    - id: unit-tests
      name: unit-tests
      entry: bash -c 'sbt test'
      language: system
      types: [file]
      pass_filenames: false
    - id: compile-integration-tests
      name: compile-integration-tests
      entry: bash -c 'sbt it:compile'
      language: system
      types: [file]
      pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks: 
    - id: check-yaml
